version: '3.8'

services:
  s_proxy:
    container_name: c_proxy
    image: nginx:1.25.5
    restart: always
    networks:
      - net-crm
    ports:
      - 80:80
    volumes:
      - /opt/docker-crm/proxy/data/default.conf:/etc/nginx/conf.d/default.conf

networks:
  net-crm:
    name: net-crm
    external: true
